{% set name = "asciidoctor" %}
{% set version = "2.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: c4120b16f7c054ee39e755b5b8cee6b248facaa4ec56b7ce493fd646aa8c744c

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r asciidoctor -e 'exit 0'
    - asciidoctor -V

about:
  home: https://asciidoctor.org
  license: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: A fast, open source text processor and publishing toolchain for converting AsciiDoc content to HTML 5, DocBook 5, and other formats.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - awvwgk
